version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '7001:8025'

    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "7005:80"
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root

    mysql:
        image: 'mysql:8.0'
        working_dir: /api
        volumes:
            - './api:/api'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=webcup_api
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        ports:
            - '7002:3306'

    api-server:
        depends_on:
            -   mysql
        image: 'nginx:alpine'
        working_dir: /api
        volumes:
            - './api:/api'
            - './infra/docker/nginx/nginx-api.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '4641:80'

    api-php-fpm:
        build: infra/docker/php-fpm
        working_dir: /api
        volumes:
            - './api:/api'
            - './infra/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
            - './infra/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
